version: '3.9'
services:
  mediamtx:
    image: bluenviron/mediamtx:1.20.1@sha256:1b029d11049be75630e9b73bb0d5f47b08a7db4eaee89a80bf8f53bc40e56414
    hostname: mediamtx
    container_name: seccam__mediamtx

    restart: unless-stopped

    volumes:
      - type: bind
        source: ./mediamtx.yml
        target: /mediamtx.yml
        read_only: true

    networks:
      - default

    deploy:
      resources:
        limits:
          memory: 256m

  nginx:
    image: nginx:1.31.5@sha256:05b8cb60c354a44ab824ea6e7dc69b46d50762cdbe728a347a5b656e6fb3d7c4
    hostname: nginx
    container_name: seccam__nginx

    restart: unless-stopped

    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true

      - type: bind
        source: ./.htpasswd
        target: /etc/htpasswd
        read_only: true

    networks:
      - default

    deploy:
      resources:
        limits:
          memory: 128m

  cloudflared:
    image: cloudflare/cloudflared:2026.8.3@sha256:51c9cefcb4569df44e1ad403ab1d3d8065aa8e84339bcfc6aee75502e1140339
    hostname: cloudflared
    container_name: seccam__cloudflared
    restart: unless-stopped

    command: tunnel run --token ${TUNNEL_TOKEN}

    networks:
      - default

    deploy:
      resources:
        limits:
          memory: 128m

networks:
  default:
    name: seccam__default
