version: '3.9'
services:
  mediamtx:
    image: bluenviron/mediamtx:1.18.2@sha256:f8628851106cc053f9175b248050bb5f362a6e65abd72297c167a1cb5a9a3be2
    hostname: mediamtx
    container_name: seccam__mediamtx

    restart: unless-stopped

    volumes:
      - type: bind
        source: ./mediamtx.yml
        target: /mediamtx.yml
        read_only: true

    networks:
      - default

    deploy:
      resources:
        limits:
          memory: 256m

  nginx:
    image: nginx:1.31.1@sha256:5aca99593157f4ae539a5dec1092a0ad8762f8e2eb1789085a13a0f5622369f6
    hostname: nginx
    container_name: seccam__nginx

    restart: unless-stopped

    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true

      - type: bind
        source: ./.htpasswd
        target: /etc/htpasswd
        read_only: true

    networks:
      - default

    deploy:
      resources:
        limits:
          memory: 128m

  cloudflared:
    image: cloudflare/cloudflared:2026.5.1@sha256:a5b5e6fd9a372f054b9a843c219bfbcdceb54691605312a8b1ee72978bdf1aa1
    hostname: cloudflared
    container_name: seccam__cloudflared
    restart: unless-stopped

    command: tunnel run --token ${TUNNEL_TOKEN}

    networks:
      - default

    deploy:
      resources:
        limits:
          memory: 128m

networks:
  default:
    name: seccam__default
