version: '3.9'
services:
  mediamtx:
    image: bluenviron/mediamtx:1.18.2@sha256:f8628851106cc053f9175b248050bb5f362a6e65abd72297c167a1cb5a9a3be2
    hostname: mediamtx
    container_name: seccam__mediamtx

    restart: unless-stopped

    volumes:
      - type: bind
        source: ./mediamtx.yml
        target: /mediamtx.yml
        read_only: true

    networks:
      - default

    deploy:
      resources:
        limits:
          memory: 256m

  nginx:
    image: nginx:1.31.0@sha256:f923b3e6cde4d9e6bd1894cc8bbe00853ac6ce48f48bd1372e8edd63bb7a832d
    hostname: nginx
    container_name: seccam__nginx

    restart: unless-stopped

    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true

      - type: bind
        source: ./.htpasswd
        target: /etc/htpasswd
        read_only: true

    networks:
      - default

    deploy:
      resources:
        limits:
          memory: 128m

  cloudflared:
    image: cloudflare/cloudflared:2026.5.0@sha256:59bab8d3aceec09bf6bdb07d6beca0225ca5cd7ab79436a87ea97978fe1dc4f9
    hostname: cloudflared
    container_name: seccam__cloudflared
    restart: unless-stopped

    command: tunnel run --token ${TUNNEL_TOKEN}

    networks:
      - default

    deploy:
      resources:
        limits:
          memory: 128m

networks:
  default:
    name: seccam__default
